import React from 'react'
import { Dimensions } from 'react-native'

const width = Dimensions.get('screen').width
const height = Dimensions.get('screen').height

export const AppDesign = {
    
    // Auth
    splashScreen: {
        s1: {
            flex: 1,
            justifyContent: 'center',
            alignItems: 'center',
            alignContent: 'center',
            backgroundColor: '#FFFFFF',
        },
        s2: {
            flex: 1,
            justifyContent: 'center',
            alignItems: 'center',
            alignContent: 'center',
        },
        s3: {
            flex: 1
        },
        s4: {
            width: Dimensions.get('screen').width,
            height: Dimensions.get('screen').width
        }
    },
    Login: {
        s1:{ flex: 1, backgroundColor: 'white' },
        s2:{display: 'flex', justifyContent: 'flex-end', alignContent: 'flex-end', alignItems: 'flex-end', padding: 20},
        s3:{ color: '#000000', fontWeight: '600' },
        s4:{ flex: 1, justifyContent: 'center', alignContent: 'center', alignItems: 'center', paddingHorizontal: 36 },
        s5:{ alignItems: 'center', alignContent: 'center', justifyContent: 'center' },
        s6:{ marginVertical: 60, height: Dimensions.get('screen').width / 4 },
        s7:{ flexDirection: 'row', width: '100%' },
        s8:{ paddingVertical: 15, paddingHorizontal: 20, borderColor: '#00B0EB', borderWidth: 1, borderTopLeftRadius: 10, borderBottomLeftRadius: 10 },
        s9:{ color: '#000000', fontSize: 20 },
        s10:{ paddingVertical: 0, paddingHorizontal: 20, borderColor: '#00B0EB', borderWidth: 1, borderTopRightRadius: 10, borderBottomRightRadius: 10, flex: 1, borderLeftWidth: 0, alignItems: 'center', justifyContent: 'center' },
        s11:{ width: '100%', color: '#000000', fontSize: 20 },
        s12:{ marginTop: 20, width: '100%', fontSize: 20,  borderRadius: 10, paddingVertical: 5 },
        s13:{ color: '#ffffff', fontSize: 20, fontWeight: '400' },
        s14:{ color: '#8A8A8A', fontSize: 12, fontWeight: '500', marginTop: 35 },
        s15:{ flexDirection: 'row', justifyContent: 'center', alignContent: 'center', alignItems: 'center', marginTop: 7 },
        s16:{ color: '#8A8A8A', fontSize: 13, fontWeight: '500', textDecorationLine: 'underline' },
        s17:{ height: 5, width: 5, backgroundColor: 'grey', marginHorizontal: 10, borderRadius: 10 },
        s18:{ color: '#8A8A8A', fontSize: 13, fontWeight: '500', textDecorationLine: 'underline' },
        s19:{ height: 5, width: 5, backgroundColor:     'grey', marginHorizontal: 10, borderRadius: 10 },
        s20:{ color: '#8A8A8A', fontSize: 13, fontWeight: '500', textDecorationLine: 'underline' },
        s21:{ resizeMode: 'contain', height: 250, width: 250 },
    },
    OtpScreen: {
        s1: {flex: 1, backgroundColor: '#FFFFFF'},
        s2: { flexDirection: 'row', justifyContent: 'space-between', padding: 15 },
        s3: { fontSize: 20, color: '#8A8A8A' },
        s4: { justifyContent: 'center', alignContent: 'center', alignItems: 'center' },
        s5: { height: 150, width: 250, marginVertical: 40, resizeMode: 'contain' },
        s6: { color: '#05194E', fontSize: 20, fontWeight: '500' },
        s7: { color: '#05194E', fontSize: 30, fontWeight: '500', marginTop: 20 },
        s8: { borderRadius: 10, borderWidth: 2, borderColor: '#00B0EB', marginVertical: 20, borderBottomWidth: 2 },
        s9: { color: '#8A8A8A', fontSize: 20, fontWeight: '500', marginTop: 10 },
        s10: { color: '#05194E', fontSize: 20, fontWeight: '500', },
        s11: { marginTop: 30, width: '60%', fontSize: 20, borderRadius: 10, paddingVertical: 5 },
        s12: { color: '#ffffff', fontSize: 20, fontWeight: '400' },
        s13: { display: 'flex', flex: 1, justifyContent: 'flex-end', alignContent: 'flex-end', alignItems: 'flex-end' },
        s14: { resizeMode: 'contain', width: Dimensions.get('screen').width, }
    },
    OnBoarding: {
        s1: { width: Dimensions.get('screen').width, height: '100%' },
        s2: { flex: 1 },
        s3: { alignItems: 'center', alignContent: 'center', justifyContent: 'center' },
        s4: { marginVertical: 30, height: Dimensions.get('screen').width / 4 },
        s5: { flex: 1 },
        s6: { paddingHorizontal: 20, paddingBottom: 20 },
        s7: { marginTop: 20, width: '100%', fontSize: 20, backgroundColor: '#05194E', borderRadius: 10, paddingVertical: 5 },
        s8: { color: '#ffffff', fontSize: 15, fontWeight: '400' },
        s9: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', alignContent: 'center', paddingHorizontal: 20, paddingBottom: 20 },
        s10: { display: 'flex', justifyContent: 'flex-end', alignContent: 'flex-end', alignItems: 'flex-end' },
        s11: { color: '#000000', fontWeight: '400', fontSize: 15, },
        s12: { fontSize: 20, backgroundColor: '#05194E', borderRadius: 10, paddingVertical: 5, marginLeft: 20 },
        s13: { color: '#ffffff', fontSize: 15, fontWeight: '400' }
    },

    // App
    SearchCity: {
        s1: { justifyContent: 'center', alignContent: 'center', alignItems: 'center', marginBottom: 20, width: Dimensions.get('screen').width/3 },
        s2: { width: Dimensions.get('window').width / 8, height: Dimensions.get('window').width / 8, alignSelf: 'center' },
        s3: { color: '#6F6F6F', fontSize: 15, marginVertical: 10, textAlign: 'center' },
        s4: { flex: 1, backgroundColor: '#ffffff', alignItems: 'center' },
        s5: { color: '#3E414A', fontSize: 26, marginVertical: 40 },
        s6: { flexDirection: 'row', justifyContent: 'center', flexWrap: 'wrap'},
        s7: { color: '#3E414A', fontSize: 18, marginVertical: 20 },
        s8: { flexDirection: 'row', paddingVertical: 0, paddingHorizontal: 20, borderColor: '#00B0EB', borderWidth: 1, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
        s9: { width: '70%', color: '#000000', fontSize: 20, paddingLeft: 20 },
        s10: { resizeMode: 'cover', width: Dimensions.get('screen').width, marginTop: 50 },
    },
    Homepage: {
        s1: {},
        s2: {},
        s3: {},
        s4: {},
        s5: {},
        s6: {},
        s7: {},
        s8: {},
        s9: {},
        s10: {},
        s11: {},
        s12: {},
        s13: {},
        s14: {},
        s15: {},
        s16: {},
        s17: {},
        s18: {},
        s19: {},
        s20: {},
        s21: {},
        s22: {},
        s23: {},
        s24: {},
        s25: {},
    },
    ServiceBooking: {
        s1: {},
        s2: {},
        s3: {},
        s4: {},
        s5: {},
        s6: {},
        s7: {},
        s8: {},
        s9: {},
        s10: {},
        s11: {},
        s12: {},
        s13: {},
        s14: {},
        s15: {},
        s16: {},
        s17: {},
        s18: {},
        s19: {},
        s20: {},
        s21: {},
        s22: {},
        s23: {},
        s24: {},
        s25: {},
    },
    MapPage: {
        s1: {},
        s2: {},
        s3: {},
        s4: {},
        s5: {},
        s6: {},
        s7: {},
        s8: {},
        s9: {},
        s10: {},
        s11: {},
        s12: {},
        s13: {},
        s14: {},
        s15: {},
        s16: {},
        s17: {},
        s18: {},
        s19: {},
        s20: {},
        s21: {},
        s22: {},
        s23: {},
        s24: {},
        s25: {},
    },
    AddressEditPage: {
        s1: {},
        s2: {},
        s3: {},
        s4: {},
        s5: {},
        s6: {},
        s7: {},
        s8: {},
        s9: {},
        s10: {},
        s11: {},
        s12: {},
        s13: {},
        s14: {},
        s15: {},
        s16: {},
        s17: {},
        s18: {},
        s19: {},
        s20: {},
        s21: {},
        s22: {},
        s23: {},
        s24: {},
        s25: {},
    },
    ConfirmBooking: {
        s1: {},
        s2: {},
        s3: {},
        s4: {},
        s5: {},
        s6: {},
        s7: {},
        s8: {},
        s9: {},
        s10: {},
        s11: {},
        s12: {},
        s13: {},
        s14: {},
        s15: {},
        s16: {},
        s17: {},
        s18: {},
        s19: {},
        s20: {},
        s21: {},
        s22: {},
        s23: {},
        s24: {},
        s25: {},
    },
    BookingsList: {
        s1: {},
        s2: {},
        s3: {},
        s4: {},
        s5: {},
        s6: {},
        s7: {},
        s8: {},
        s9: {},
        s10: {},
        s11: {},
        s12: {},
        s13: {},
        s14: {},
        s15: {},
        s16: {},
        s17: {},
        s18: {},
        s19: {},
        s20: {},
        s21: {},
        s22: {},
        s23: {},
        s24: {},
        s25: {},
    },
    ServiceCompleted: {
        s1: {},
        s2: {},
        s3: {},
        s4: {},
        s5: {},
        s6: {},
        s7: {},
        s8: {},
        s9: {},
        s10: {},
        s11: {},
        s12: {},
        s13: {},
        s14: {},
        s15: {},
        s16: {},
        s17: {},
        s18: {},
        s19: {},
        s20: {},
        s21: {},
        s22: {},
        s23: {},
        s24: {},
        s25: {},
    },
    ServiceOngoing: {
        s1: {},
        s2: {},
        s3: {},
        s4: {},
        s5: {},
        s6: {},
        s7: {},
        s8: {},
        s9: {},
        s10: {},
        s11: {},
        s12: {},
        s13: {},
        s14: {},
        s15: {},
        s16: {},
        s17: {},
        s18: {},
        s19: {},
        s20: {},
        s21: {},
        s22: {},
        s23: {},
        s24: {},
        s25: {},
    },
    ServiceUpcoming: {
        s1: {},
        s2: {},
        s3: {},
        s4: {},
        s5: {},
        s6: {},
        s7: {},
        s8: {},
        s9: {},
        s10: {},
        s11: {},
        s12: {},
        s13: {},
        s14: {},
        s15: {},
        s16: {},
        s17: {},
        s18: {},
        s19: {},
        s20: {},
        s21: {},
        s22: {},
        s23: {},
        s24: {},
        s25: {},
    },
    CouponCode: {
        s1: {},
        s2: {},
        s3: {},
        s4: {},
        s5: {},
        s6: {},
        s7: {},
        s8: {},
        s9: {},
        s10: {},
        s11: {},
        s12: {},
        s13: {},
        s14: {},
        s15: {},
        s16: {},
        s17: {},
        s18: {},
        s19: {},
        s20: {},
        s21: {},
        s22: {},
        s23: {},
        s24: {},
        s25: {},
    },
    Review: {
        s1: {},
        s2: {},
        s3: {},
        s4: {},
        s5: {},
        s6: {},
        s7: {},
        s8: {},
        s9: {},
        s10: {},
        s11: {},
        s12: {},
        s13: {},
        s14: {},
        s15: {},
        s16: {},
        s17: {},
        s18: {},
        s19: {},
        s20: {},
        s21: {},
        s22: {},
        s23: {},
        s24: {},
        s25: {},
    },
    Profile: {
        s1: {},
        s2: {},
        s3: {},
        s4: {},
        s5: {},
        s6: {},
        s7: {},
        s8: {},
        s9: {},
        s10: {},
        s11: {},
        s12: {},
        s13: {},
        s14: {},
        s15: {},
        s16: {},
        s17: {},
        s18: {},
        s19: {},
        s20: {},
        s21: {},
        s22: {},
        s23: {},
        s24: {},
        s25: {},
    },
    AddressPage: {
        s1: {},
        s2: {},
        s3: {},
        s4: {},
        s5: {},
        s6: {},
        s7: {},
        s8: {},
        s9: {},
        s10: {},
        s11: {},
        s12: {},
        s13: {},
        s14: {},
        s15: {},
        s16: {},
        s17: {},
        s18: {},
        s19: {},
        s20: {},
        s21: {},
        s22: {},
        s23: {},
        s24: {},
        s25: {},
    },
    Reward: {
        s1: {},
        s2: {},
        s3: {},
        s4: {},
        s5: {},
        s6: {},
        s7: {},
        s8: {},
        s9: {},
        s10: {},
        s11: {},
        s12: {},
        s13: {},
        s14: {},
        s15: {},
        s16: {},
        s17: {},
        s18: {},
        s19: {},
        s20: {},
        s21: {},
        s22: {},
        s23: {},
        s24: {},
        s25: {},
    },
    ContactUs: {
        s1: {},
        s2: {},
        s3: {},
        s4: {},
        s5: {},
        s6: {},
        s7: {},
        s8: {},
        s9: {},
        s10: {},
        s11: {},
        s12: {},
        s13: {},
        s14: {},
        s15: {},
        s16: {},
        s17: {},
        s18: {},
        s19: {},
        s20: {},
        s21: {},
        s22: {},
        s23: {},
        s24: {},
        s25: {},
    },
    AboutUs: {
        s1: {},
        s2: {},
        s3: {},
        s4: {},
        s5: {},
        s6: {},
        s7: {},
        s8: {},
        s9: {},
        s10: {},
        s11: {},
        s12: {},
        s13: {},
        s14: {},
        s15: {},
        s16: {},
        s17: {},
        s18: {},
        s19: {},
        s20: {},
        s21: {},
        s22: {},
        s23: {},
        s24: {},
        s25: {},
    },
    PersonalDetails: {
        s1: {},
        s2: {},
        s3: {},
        s4: {},
        s5: {},
        s6: {},
        s7: {},
        s8: {},
        s9: {},
        s10: {},
        s11: {},
        s12: {},
        s13: {},
        s14: {},
        s15: {},
        s16: {},
        s17: {},
        s18: {},
        s19: {},
        s20: {},
        s21: {},
        s22: {},
        s23: {},
        s24: {},
        s25: {},
    },
};